apiVersion: v1
kind: Service
metadata:
  name: risotto-play
spec:
  selector:
    app: risotto-play
  ports:
    - port: 80
      targetPort: 4000
      name: api
      protocol: TCP
  type: NodePort
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: domain-ingress
spec:
  rules:
  - host: api.play.risotto.dev
    http:
      paths:
      - backend:
          serviceName: risotto-play
          servicePort: 80
  tls:
  - hosts:
    - api.play.risotto.dev
    secretName: risottosecret-tls

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: basic-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           serviceName: risotto-play
#           servicePort: 8080