name: Publish image and Deploy

on: push

jobs:
  publish-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          docker build --target tester -t risotto-play-tester .
      - id: run-tests
        run: |
          docker run risotto-play-tester
      - id: build
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: jjhaslanded/risotto-play
          tags: latest,${{ event.run_id }}
          target: runner
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      - uses: Azure/k8s-deploy@v1
        if: github.ref == 'master' # Only deploy from master branch
        with:
          namespace: 'jamesjarvis'
          manifests: |
            deployments/deployment-api.yml
            deployments/service-api.yml
          images: "jjhaslanded/risotto-play:${{ event.run_id }}"
          kubectl-version: "latest"
