name: Publish docker

on: push

jobs:
  publish-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: build
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: jjhaslanded/risotto-play
          auto_tag: true
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'jamesjarvis'
          manifests: |
            deployments/deployment-api.yml
            deployments/service-api.yml
          images: "${{ steps.build.outputs.tag }}"
          kubectl-version: "latest"
