name: Publish image and Deploy

on: push

jobs:
  publish-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          docker build --target tester -t risotto-play-tester .
      - id: run-tests
        run: |
          docker run --rm -iv${PWD}:/host-volume risotto-play-tester
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          name: codecov-umbrella
          fail_ci_if_error: true
      - id: build
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: jjhaslanded/risotto-play
          tags: latest,${{ github.run_id }}
          target: runner
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Only deploy from master branch
    needs: [publish-api]
    env:
      COMPOSE_PROJECT_NAME: risotto_play_api
      DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@master
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Build & Deploy
        run: PORT=5000 TAG="${{ github.run_id }}" docker-compose --compatibility up --build -d
